# Generated by Django 5.2.5 on 2025-08-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
    ]
