# Generated by Django 5.2.5 on 2025-08-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop1", "0002_remove_post_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="user",
        ),
    ]
