# Generated by Django 5.2.5 on 2025-08-28 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop1", "0004_comment_parent_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True,
                related_name="disliked_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True, related_name="disliked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
