# Generated by Django 5.2.6 on 2025-10-02 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop1", "0010_story_likes_storycomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="viewers",
            field=models.ManyToManyField(
                blank=True, related_name="viewed_stories", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
