# Generated by Django 5.2.6 on 2025-10-02 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop1", "0014_message_parent_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="seen_by",
            field=models.ManyToManyField(
                blank=True, related_name="seen_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
