# Generated by Django 5.2.6 on 2025-10-03 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop1", "0015_message_seen_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
