# Generated by Django 5.2.6 on 2025-10-03 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop1", "0016_message_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="shared_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop1.post",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
