# Generated by Django 5.2.6 on 2025-10-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop1", "0017_message_shared_post_alter_message_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="direct_messages/"),
        ),
    ]
