# Generated by Django 5.2.6 on 2025-10-06 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop1", "0018_message_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_view_once",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="viewed_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="viewed_once_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
