# Generated by Django 5.2.6 on 2025-10-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop1", "0019_message_is_view_once_message_viewed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="view_once_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
