# Generated by Django 5.2.6 on 2025-10-06 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop1", "0020_message_view_once_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="thread",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
